---
abstract: 'Extensions to L<MooseX::Types::DateTime>'
author:
  - 'John Napiorkowski <jjn1056 at yahoo.com>'
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0.27
  Test::More: 0
  Test::use::ok: 0.02
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-DateTime-MoreCoercions
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0.4302
  DateTime::Duration: 0.4302
  DateTimeX::Easy: 0.085
  Moose: 0.41
  MooseX::Types: 0.04
  MooseX::Types::DateTime: 0.07
  MooseX::Types::Moose: 0.04
  Time::Duration::Parse: 0.06
  namespace::clean: 0.08
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.moose.perl.org/MooseX-Types-DateTime-MoreCoercions.git
version: 0.10
